---
- name: Update all packages to the latest version
  yum:
    name: "*"
    state: latest

- name: Install required dependencies
  yum:
    name: 
      - git
      - yum-utils
    state: present

# Install OpenJDK 11
- name: Add Amazon Corretto repository
  yum_repository:
    name: corretto
    description: Amazon Corretto
    baseurl: https://yum.corretto.aws
    gpgcheck: yes
    gpgkey: https://yum.corretto.aws/corretto.key
    state: present

- name: Install Amazon Corretto 11 (OpenJDK 11)
  yum:
    name: java-11-amazon-corretto-devel
    state: present


# Install Jenkins
- name: install jenkins
  yum_repository:
    name: jenkins
    description: Jenkins
    baseurl: http://pkg.jenkins.io/redhat/jenkins.repo
    gpgcheck: yes
    gpgkey: http://pkg.jenkins.io/redhat-stable/jenkins.io-2023
    state: present


      

